name: Sync fork with upstream
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch: 

jobs:
  sync-fork:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: thiagokokada/merge-upstream@v1.0.2
        with:
          branch: main
